# Generated by Django 2.2 on 2019-05-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_data',
        ),
    ]
