# Generated by Django 2.2 on 2019-05-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_cartm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartm',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CartM',
        ),
    ]
