# Generated by Django 2.2 on 2019-05-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_usercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='username',
            new_name='user',
        ),
    ]
