# Generated by Django 2.2 on 2019-05-20 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190519_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='updated',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='timestamp',
            new_name='update',
        ),
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name=shop.models.Product),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name=shop.models.Product),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
