# Generated by Django 2.2 on 2019-05-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20190520_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_data',
        ),
    ]
