# Generated by Django 2.2 on 2019-05-20 04:11

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20190520_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name=shop.models.Product),
        ),
    ]
