# Generated by Django 2.2 on 2019-05-20 04:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20190520_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=shop.models.Product),
        ),
    ]
