# Generated by Django 2.2 on 2019-05-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20190520_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='timestamp',
        ),
    ]
