# Generated by Django 2.2 on 2019-06-04 03:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20190604_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
