# Generated by Django 2.2 on 2019-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190518_1314'),
        ('cart', '0026_auto_20190604_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_id',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
