# Generated by Django 2.2 on 2019-06-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_auto_20190604_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='id',
        ),
        migrations.AddField(
            model_name='usercart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
