# Generated by Django 2.2 on 2019-06-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_usercart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product_id',
            new_name='prod',
        ),
    ]
