# Generated by Django 2.2 on 2019-08-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_auto_20190613_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='prod',
        ),
    ]
